name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests

    - name: Build Docker image
      run: |
        docker build -t docker-flask-ci .
        
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ~/docker-flask-ci
          git pull origin main
          docker stop docker-flask-ci || true
          docker rm docker-flask-ci || true
          docker build -t docker-flask-ci .
          docker run -d --name docker-flask-ci -p 127.0.0.1:5000:5000 docker-flask-ci
